name: Java CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: 'gradle'
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Start docker compose for integration tests
      run: docker-compose -f docker/docker-compose.yml up -d

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run build with Gradle wrapper
      id: gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew --info --scan --no-daemon build jacocoTestReport sonarqube

    - name: Upload build reports
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: build-reports
        path: build/reports/

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: kafka-gitops.jar
        path: build/libs/kafka-gitops-all.jar
