name: Java CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Start docker compose for integration tests
      run: docker-compose -f docker/docker-compose.yml up -d

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run build with Gradle wrapper
      id: gradle
      run: ./gradlew --info --scan build jacocoTestReport

    - name: Upload build reports
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: build-reports
        path: build/reports/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./build/reports/jacoco/report.xml

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: kafka-gitops.jar
        path: build/libs/kafka-gitops-all.jar
