name: Java CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Start docker compose for integration tests
      run: docker-compose -f docker/docker-compose.yml up -d

    - name: Build with Gradle
      run: ./gradlew --info build jacocoTestReport

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./build/reports/jacoco/report.xml

    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: kafka-gitops.jar
        path: build/libs/kafka-gitops-all.jar
